@echo off
echo Starting Video SEO Analysis System...

echo Starting backend server...
start cmd /k "cd backend && python app.py"

echo Waiting for backend to start...
timeout /t 5 /nobreak > nul

echo Starting frontend server...
start cmd /k "cd frontend && set PORT=3000 && npm start"

echo Both servers are starting. Please wait...
echo Backend will be available at http://localhost:8000
echo Frontend will be available at http://localhost:3000
